name: Checks

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: check_changes
        with:
          filters: |
            relevant:
              - '**/*.py'
              - '**/*.sh'
              - '**/*.json'
              - '**/*.html'
              - '**/*.toml'
              - '**/*.lock'
              - 'tests/**/*.yaml'
              - '.python-version'
              - '.Dockerfile'
      
      - name: Skip message
        if: ${{ !(steps.check_changes.outputs.relevant == 'true') }}
        run: echo "Skipping Python checks - no relevant changes detected"


      - name: Setup project
        if: steps.check_changes.outputs.relevant == 'true'
        uses: ./.github/actions/setup

      - name: Run linting
        if: steps.check_changes.outputs.relevant == 'true'
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
        with: 
          args: check --fix
      
      - name: Run formatting
        if: steps.check_changes.outputs.relevant == 'true'
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
        with: 
          args: format
    
      - name: Type checking
        if: steps.check_changes.outputs.relevant == 'true'
        uses: jakebailey/pyright-action@8ec14b5cfe41f26e5f41686a31eb6012758217ef
        with:
          project: pyproject.toml
          python-path: .venv/bin/python
          extra-args: amati 

      - name: Testing
        if: steps.check_changes.outputs.relevant == 'true'
        run: uv run pytest -m"not external" --cov

      - name: Doctests
        if: steps.check_changes.outputs.relevant == 'true'
        run: uv run pytest --doctest-modules amati/

      - name: Coverage comment
        if: steps.check_changes.outputs.relevant == 'true'
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@7188638f871f721a365d644f505d1ff3df20d683 # v3
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_COMMENT_TOKEN }}
        continue-on-error: true

      - name: Store Pull Request comment to be posted
        if: steps.check_changes.outputs.relevant == 'true'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
